services:

  dev-backend:
    build:
      context: ./backend/dev
      dockerfile: Dockerfile
    container_name: dev-backend
    env_file:
      - ./backend/dev/.env
    ports:
      - "3000:3000"
    networks:
      - app-net

  prod-backend:
    build:
      context: ./backend/prod
      dockerfile: Dockerfile
    container_name: prod-backend
    env_file:
      - ./backend/prod/.env
    ports:
      - "3001:3001"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_DEV_API=http://dev-backend:3000
      - REACT_APP_PROD_API=http://prod-backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - dev-backend
      - prod-backend
    networks:
      - app-net

networks:
  app-net:

