services:

  dev-backend:
    build:
      context: ./backend/dev
      dockerfile: Dockerfile
    container_name: dev-backend
    env_file:
      - ./backend/dev/.env
    ports:
      - "3001:3001"
    depends_on:
      - dev-mongo
    networks:
      - app-net

  dev-mongo:
    image: mongo
    container_name: dev-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net

  prod-backend:
    build:
      context: ./backend/prod
      dockerfile: Dockerfile
    container_name: prod-backend
    env_file:
      - ./backend/prod/.env
    ports:
      - "3002:3002"
    depends_on:
      - prod-mongo
    networks:
      - app-net

  prod-mongo:
    image: mongo
    container_name: prod-mongo
    ports:
      - "27018:27017"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_DEV_API=http://dev-backend:3001/api/tickets
      - REACT_APP_PROD_API=http://prod-backend:3002/api/tickets
    ports:
      - "3000:3000"
    depends_on:
      - dev-backend
      - prod-backend
    networks:
      - app-net

networks:
  app-net:
